[package]
name = "foo"
version = "0.1.0"
mode = "cs-module"
description = "An empty test module"
repository = ""
authors = ["tizio", "caio"]
license = ""
cs_version = "7.0"
include = ["src"]

[main]
src = "src"
udo = "src/foo.udo"

[dependencies]
bar = "0.1.0"
