[package]
name = "bar"
version = "0.1.0"
mode = "cs-module"
description = "Another empty test module"
repository = ""
authors = ["tiziob"]
license = ""
cs_version = "7.0"
include = ["src"]

[main]
src = "src"
udo = "src/bar.udo"
